USE                      equipo_de_futbol_bastardmunchen;

SELECT * FROM JugadoresDestacados;
SELECT * FROM EntrenadoresPorNacionalidad;
SELECT * FROM PartidosPendientes;

DELIMITER $$
CREATE FUNCTION CalcularEdad(FECHANACIMIENTO DATE)
RETURNS INT
DETERMINISTIC
BEGIN
    RETURN YEAR(CURDATE()) - YEAR(FECHANACIMIENTO) - (RIGHT(CURDATE(), 5) < RIGHT(FECHANACIMIENTO, 5));
END $$
DELIMITER ;


DELIMITER $$
CREATE FUNCTION SalarioPromedioEquipo(EQUIPOID INT)
RETURNS DECIMAL(10,2)
READS SQL DATA
BEGIN
    DECLARE promedio DECIMAL(10,2);
    SELECT AVG(SALARIO) INTO promedio FROM JUGADORES WHERE EQUIPOID = EQUIPOID;
    RETURN promedio;
END $$
DELIMITER ;